"""
This is a setup.py script originally generated by py2applet but
maintained manually

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob
from conedevelopment_files import version

NAME = "ConeDevelopment"
VERSION = version.getVersionFromScm()

APP = ['conedevelopment_files/ConeDevelopment.py']
DATA_FILES = \
    glob('conedevelopment_files/*.png') +\
    glob('conedevelopment_files/*.jpg') +\
    glob('conedevelopment_files/*.ico') +\
    glob('conedevelopment_files/*.html') +\
    glob('conedevelopment_files/*.ini') +\
    glob('conedevelopment_files/sample_pics') \
#    glob('conedevelopment_files/sample_pics/*') \


EXT_PACKAGES = ['PIL', 'reportlab', 'simplejson', 'wx']

# A custom plist for letting it associate with all files.
PLIST = dict(
    CFBundleDocumentTypes=[
        dict(CFBundleTypeExtensions=["conedevelopment"],
             CFBundleTypeName="ConeDevelopment Document",
             CFBundleTypeRole="Editor"),
        ],
#    CFBundleGetInfoString="The text shown by Finder's Get Info panel."
#    CFBundleIconFile=NAME,
    CFBundleName=NAME,
    CFBundleShortVersionString=VERSION,
    CFBundleGetInfoString=' '.join([NAME, VERSION]),
    CFBundleExecutable=NAME,
    CFBundleIdentifier='digital.bauermeister.software.conedevelopment',
    )

PY2APP_OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'conedevelopment.icns',
    'plist': PLIST,
    'includes': EXT_PACKAGES,
    'optimize': 0, # >0 will crash the app :-(
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': PY2APP_OPTIONS},
    setup_requires=['py2app'],
)
